/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DebitEntry {
  'id' : bigint,
  'flatId' : bigint,
  'date' : string,
  'description' : string,
  'amount' : bigint,
}
export interface Expense {
  'id' : bigint,
  'date' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FlatOwner {
  'id' : bigint,
  'ownerName' : string,
  'password' : string,
  'flatStatus' : string,
  'block' : string,
  'ownerMobile' : string,
  'flatNumber' : string,
  'maintenanceAmount' : bigint,
  'openingBalance' : bigint,
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'postedDate' : string,
  'createdBy' : string,
  'description' : string,
  'category' : string,
  'attachmentName' : [] | [string],
  'attachment' : [] | [ExternalBlob],
}
export interface Payment {
  'id' : bigint,
  'flatId' : bigint,
  'date' : string,
  'paymentMode' : string,
  'receiptId' : string,
  'amount' : bigint,
}
export interface SocietyProfile {
  'name' : string,
  'address' : string,
  'licenseNumber' : string,
  'voucherCategories' : Array<string>,
}
export interface UserProfile {
  'flatId' : [] | [bigint],
  'name' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDebitEntry' : ActorMethod<[DebitEntry], bigint>,
  'addExpense' : ActorMethod<[Expense], bigint>,
  'addFlatOwner' : ActorMethod<[FlatOwner], bigint>,
  'addNotice' : ActorMethod<[Notice], bigint>,
  'addNoticeManual' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [string],
      string,
      string,
    ],
    bigint
  >,
  'addPayment' : ActorMethod<[Payment], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateMonthlyDebit' : ActorMethod<[string, string], undefined>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDebitEntry' : ActorMethod<[bigint], [] | [DebitEntry]>,
  'getExpense' : ActorMethod<[bigint], [] | [Expense]>,
  'getFlatOwner' : ActorMethod<[bigint], [] | [FlatOwner]>,
  'getFlatStatement' : ActorMethod<
    [bigint],
    { 'credits' : Array<Payment>, 'debits' : Array<DebitEntry>, 'openingBalance' : bigint }
  >,
  'getNotice' : ActorMethod<[bigint], [] | [Notice]>,
  'getNoticesByCategory' : ActorMethod<[string], Array<Notice>>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getPendingAmount' : ActorMethod<[bigint], bigint>,
  'getPendingFlats' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'ownerName' : string,
        'password' : string,
        'flatStatus' : string,
        'block' : string,
        'pendingAmount' : bigint,
        'ownerMobile' : string,
        'flatNumber' : string,
        'maintenanceAmount' : bigint,
        'openingBalance' : bigint,
      }
    >
  >,
  'getSocietyProfile' : ActorMethod<[], [] | [SocietyProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetFinancialData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFlatOwner' : ActorMethod<[FlatOwner], undefined>,
  'updateSocietyProfile' : ActorMethod<[SocietyProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];