/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DebitEntry = IDL.Record({
  'id' : IDL.Nat,
  'flatId' : IDL.Nat,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const FlatOwner = IDL.Record({
  'id' : IDL.Nat,
  'ownerName' : IDL.Text,
  'password' : IDL.Text,
  'flatStatus' : IDL.Text,
  'block' : IDL.Text,
  'ownerMobile' : IDL.Text,
  'flatNumber' : IDL.Text,
  'maintenanceAmount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedDate' : IDL.Text,
  'createdBy' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'attachmentName' : IDL.Opt(IDL.Text),
  'attachment' : IDL.Opt(ExternalBlob),
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'flatId' : IDL.Nat,
  'date' : IDL.Text,
  'paymentMode' : IDL.Text,
  'receiptId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'flatId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'mobile' : IDL.Text,
});
export const SocietyProfile = IDL.Record({
  'name' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'voucherCategories' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDebitEntry' : IDL.Func([DebitEntry], [IDL.Nat], []),
  'addExpense' : IDL.Func([Expense], [IDL.Nat], []),
  'addFlatOwner' : IDL.Func([FlatOwner], [IDL.Nat], []),
  'addNotice' : IDL.Func([Notice], [IDL.Nat], []),
  'addNoticeManual' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addPayment' : IDL.Func([Payment], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateMonthlyDebit' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDebitEntry' : IDL.Func([IDL.Nat], [IDL.Opt(DebitEntry)], ['query']),
  'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getFlatOwner' : IDL.Func([IDL.Nat], [IDL.Opt(FlatOwner)], ['query']),
  'getFlatStatement' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'credits' : IDL.Vec(Payment),
          'debits' : IDL.Vec(DebitEntry),
        }),
      ],
      ['query'],
    ),
  'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
  'getNoticesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Notice)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getPendingAmount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getPendingFlats' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'ownerName' : IDL.Text,
            'password' : IDL.Text,
            'flatStatus' : IDL.Text,
            'block' : IDL.Text,
            'pendingAmount' : IDL.Nat,
            'ownerMobile' : IDL.Text,
            'flatNumber' : IDL.Text,
            'maintenanceAmount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getSocietyProfile' : IDL.Func([], [IDL.Opt(SocietyProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFlatOwner' : IDL.Func([FlatOwner], [], []),
  'updateSocietyProfile' : IDL.Func([SocietyProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DebitEntry = IDL.Record({
    'id' : IDL.Nat,
    'flatId' : IDL.Nat,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const FlatOwner = IDL.Record({
    'id' : IDL.Nat,
    'ownerName' : IDL.Text,
    'password' : IDL.Text,
    'flatStatus' : IDL.Text,
    'block' : IDL.Text,
    'ownerMobile' : IDL.Text,
    'flatNumber' : IDL.Text,
    'maintenanceAmount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedDate' : IDL.Text,
    'createdBy' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'attachmentName' : IDL.Opt(IDL.Text),
    'attachment' : IDL.Opt(ExternalBlob),
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'flatId' : IDL.Nat,
    'date' : IDL.Text,
    'paymentMode' : IDL.Text,
    'receiptId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'flatId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const SocietyProfile = IDL.Record({
    'name' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'voucherCategories' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDebitEntry' : IDL.Func([DebitEntry], [IDL.Nat], []),
    'addExpense' : IDL.Func([Expense], [IDL.Nat], []),
    'addFlatOwner' : IDL.Func([FlatOwner], [IDL.Nat], []),
    'addNotice' : IDL.Func([Notice], [IDL.Nat], []),
    'addNoticeManual' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addPayment' : IDL.Func([Payment], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateMonthlyDebit' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDebitEntry' : IDL.Func([IDL.Nat], [IDL.Opt(DebitEntry)], ['query']),
    'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getFlatOwner' : IDL.Func([IDL.Nat], [IDL.Opt(FlatOwner)], ['query']),
    'getFlatStatement' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'credits' : IDL.Vec(Payment),
            'debits' : IDL.Vec(DebitEntry),
          }),
        ],
        ['query'],
      ),
    'getNotice' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
    'getNoticesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Notice)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getPendingAmount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getPendingFlats' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'ownerName' : IDL.Text,
              'password' : IDL.Text,
              'flatStatus' : IDL.Text,
              'block' : IDL.Text,
              'pendingAmount' : IDL.Nat,
              'ownerMobile' : IDL.Text,
              'flatNumber' : IDL.Text,
              'maintenanceAmount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getSocietyProfile' : IDL.Func([], [IDL.Opt(SocietyProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFlatOwner' : IDL.Func([FlatOwner], [], []),
    'updateSocietyProfile' : IDL.Func([SocietyProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };